### ISSUE TITLE
How to install the neovim config?

### ISSUE THREAD

**Issue by Himujjal** [emilienlemaire/dotfiles-arch#1]
I would like to use your neovim config as setting up my own is a drag. I cloned this repo and copied the /dotfiles/nvim folder contents to ~/.config/nvim.

What command to put next, to install the plugins and all?

**Comment by emilienlemaire** [comment]
To install the plugins you should use [packer.nvim](https://github.com/wbthomason/packer.nvim).
However I would recommend against just copying the entire config. I think you should look at the bits you think might help you and trying to understand how it works, and making it fit your needs. My config is very much fitted to my use cases and might not be good for yours.

**Comment by Himujjal** [comment]
I was looking at a sample vim config file to learn. I wanted to try the whole thing out before going through bits and pieces though. Of course I will need to go through everything later.
